/**
 * Shared helpers for teacher dashboards that ingest base64-encoded
 * export codes generated by student tools.
 */

export interface ExportPayload<TData = unknown> {
  toolId: string;
  studentName: string;
  timestamp: string;
  data: TData;
}

/**
 * Decode a base64-encoded UTF-8 JSON export code. Returns null on any error.
 */
export function decodePayload<TData = unknown>(code: string): ExportPayload<TData> | null {
  try {
    const trimmed = code.trim();
    if (!trimmed) return null;
    // Match the encoder used by the student tools:
    //   btoa(unescape(encodeURIComponent(json)))
    const decoded = decodeURIComponent(escape(atob(trimmed)));
    const parsed = JSON.parse(decoded);
    if (
      typeof parsed !== 'object' ||
      parsed === null ||
      typeof parsed.toolId !== 'string' ||
      typeof parsed.studentName !== 'string' ||
      typeof parsed.timestamp !== 'string' ||
      !('data' in parsed)
    ) {
      return null;
    }
    return parsed as ExportPayload<TData>;
  } catch {
    return null;
  }
}

export function formatTimestamp(ts: string): string {
  const d = new Date(ts);
  if (isNaN(d.getTime())) return ts;
  return d.toLocaleString(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

/**
 * Build a CSV string from a header row and body rows. Each cell is escaped:
 * anything containing a comma, quote, or newline is quoted with doubled inner quotes.
 */
export function toCsv(header: string[], rows: (string | number | null | undefined)[][]): string {
  const escape = (v: string | number | null | undefined) => {
    const s = v == null ? '' : String(v);
    if (/[",\r\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
    return s;
  };
  const lines = [header.map(escape).join(',')];
  for (const row of rows) lines.push(row.map(escape).join(','));
  return lines.join('\r\n');
}

/**
 * Trigger a browser download of a text blob.
 */
export function downloadFile(filename: string, contents: string, mime = 'text/csv;charset=utf-8') {
  const blob = new Blob([contents], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function wordCount(s: string | undefined | null): number {
  if (!s) return 0;
  const trimmed = s.trim();
  if (!trimmed) return 0;
  return trimmed.split(/\s+/).length;
}
